rules:
  - name: commit title scope
    description: all commit titles must have a lowercase scope
    expression:  |-
      .commits all((.title test "^[a-z1-9/*,:_-]+:") or (.title test "^Revert"))

  - name: commit title length
    description: all commit titles must be no more than 50 characters
    expression:  |-
      .commits all((.title length < 51) or (.title test "^Revert"))

  - name: commit description
    description: all commits must have a description with each line having no more than 72 characters
    expression: |-
      .commits all((.description lines all(. length < 73) and (.description lines length > 0)) or (.title test "^Revert") or (.title test "^version"))
