[package]
name = "coreos-metadata"
version = "0.1.0"
authors = ["Stephen Demos <stephen.demos@coreos.com>"]

[[bin]]
name = "coreos-metadata"
path = "src/bin/coreos-metadata.rs"

[dependencies]
clap = "*"
users = "*"
slog-term = "*"
slog-async = "*"
slog-scope = "*"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2"
serde_json = "1.0"
openssl = "0.9.17"
base64 = "0.6"
byteorder = "1.1"
pnet = "0.19"
reqwest = "0.7"
hyper = "0.11"
error-chain = { version = "0.11", default-features = false }
openssh-keys = "0.1"
update-ssh-keys = { git = "https://github.com/sdemos/update-ssh-keys-rs" }
ipnetwork = "0.12"
clippy = { version = "*", optional = true }
hostname = "0.1"

[dependencies.slog]
version = "*"
features = ["max_level_trace"]

[dev-dependencies]
mockito = "0.9"

[features]
default = []
lints = ["clippy"]
