[package]
name = "coreos-metadata"
version = "0.1.0"
authors = ["Stephen Demos <stephen.demos@coreos.com>"]

[dependencies]
clap = "*"
users = "*"
slog-term = "*"
slog-async = "*"
slog-scope = "*"

[dependencies.slog]
version = "*"
features = ["max_level_trace"]
